/**
 * The strategy used to produce a locator, in priority order
 * following Playwright's own recommendations.
 */
export type LocatorStrategy =
  | 'getByRole'
  | 'getByLabel'
  | 'getByPlaceholder'
  | 'getByText'
  | 'getByAltText'
  | 'getByTitle'
  | 'getByTestId'
  | 'css'
  | 'xpath';

/**
 * A single resolved locator with metadata.
 */
export interface ResolvedLocator {
  /** The Playwright locator expression, e.g. page.getByRole('button', { name: 'Submit' }) */
  expression: string;
  /** The strategy used */
  strategy: LocatorStrategy;
  /**
   * Confidence score 0–100.
   * Higher = more resilient to markup changes.
   */
  confidence: number;
  /** Whether this locator uniquely matched a single element during validation */
  isUnique?: boolean;
}

/**
 * A serialisable description of a DOM element, passed from the
 * browser context (content script / Playwright page.evaluate) to the engine.
 */
export interface ElementDescriptor {
  tagName: string;
  role: string | null;
  accessibleName: string | null;
  labelText: string | null;
  placeholder: string | null;
  altText: string | null;
  title: string | null;
  innerText: string | null;
  testId: string | null;
  id: string | null;
  name: string | null;
  classList: string[];
  /** Full CSS selector path generated by the browser */
  cssPath: string;
  /** XPath */
  xpath: string;
}

/**
 * Result returned by the engine for a single element.
 */
export interface LocatorResult {
  descriptor: ElementDescriptor;
  /** Ordered best-to-worst list of locators */
  locators: ResolvedLocator[];
  /** The top recommended locator */
  best: ResolvedLocator;
}
